Island interface
lukasz-kukulka/SHM-Dream-team- pull request #6
Opened 2021-10-21 16:25 UTC by lukasz-kukulka

2021-10-21 17:37 UTC, runer53248 requested changes

2021-10-21 17:37 UTC, runer53248 commented on include/game/IslandInterface.hpp
> +private:
Remove private section and members.

2021-10-21 17:37 UTC, runer53248 commented on include/game/IslandInterface.hpp
> +    std::string getName() const { return name_; }
Remove implementation and make methods pure virtual.

2021-10-21 17:37 UTC, runer53248 commented on include/game/IslandInterface.hpp
> +    IslandInterface(std::string& name, std::unique_ptr<Coordinates>& position, int level_);
Remove constructor from interface.

2021-10-22 11:59 UTC, runer53248 requested changes

2021-10-22 11:59 UTC, runer53248 commented on include/game/Island.hpp
> +    ~Island() override;
D-tor not needed (use rule of 0).

2021-10-22 11:59 UTC, runer53248 commented on game/Island.cpp
> +    , position_(std::make_unique<Coordinates>(*position))
Use std::move or remove unique_ptr in argument type.
Get string by const &.

2021-10-22 11:59 UTC, runer53248 commented on include/game/IslandInterface.hpp
> +};
Looks good.

2021-10-22 12:02 UTC, Martyna-Tu commented on include/game/Island.hpp
> +    ~Island() override;
in my opinion, it will be better to write : ~Island() override = default; 
and remove d-tor from cpp flie

2021-10-22 13:09 UTC, lukasz-kukulka commented on include/game/Island.hpp
> +    ~Island() override;
Done

2021-10-22 13:10 UTC, lukasz-kukulka commented on game/Island.cpp
> +    , position_(std::make_unique<Coordinates>(*position))
I'm thinking is done, please confirm if is OK

2021-10-22 13:11 UTC, lukasz-kukulka commented on include/game/Island.hpp
> +    ~Island() override;
I used advice from @runer53248 about rule 0, if you don't mind

2021-10-22 13:28 UTC, runer53248 requested changes

2021-10-22 13:28 UTC, runer53248 commented on game/Island.cpp
> +    , position_(std::make_unique<Coordinates>(std::move(position)))
Dont use make_unique in initialization list. 
To complex for so simple operation and hard to read and thinking about.

2021-10-22 13:28 UTC, runer53248 commented on include/game/Island.hpp
> +    Island(const std::string& name, std::unique_ptr<Coordinates>& position, int level);
Remove & from unique_ptr - it will meaning that island take responsibility for Coordinate 
or dont use smart pointer here.

2021-10-22 14:26 UTC, lukasz-kukulka commented on game/Island.cpp
> +    , position_(std::make_unique<Coordinates>(std::move(position)))
Changed

2021-10-22 14:26 UTC, lukasz-kukulka commented on include/game/Island.hpp
> +    Island(const std::string& name, std::unique_ptr<Coordinates>& position, int level);
Changed

2021-10-22 15:47 UTC, runer53248 commented on include/game/Island.hpp
> +    std::string getName() const override { return name_; }
Implementation can be moved to cpp file.

2021-10-22 15:52 UTC, runer53248 requested changes

2021-10-22 15:52 UTC, runer53248 commented on include/game/Island.hpp
> +    Coordinates* getCoordinates() const override { return position_.get(); }
No longer smart pointer - dont have get and return Coordinates*.

2021-10-22 15:52 UTC, runer53248 commented on include/game/Island.hpp
> +    std::string name_;
Posibly can be const (name_ and position_).

2021-10-24 05:17 UTC, lukasz-kukulka commented on include/game/Island.hpp
> +    std::string getName() const override { return name_; }
What is the reason to move this in .cpp?

2021-10-24 11:55 UTC, runer53248 approved these changes

2021-10-24 11:56 UTC, merged